### ISSUE TITLE
Apache Podling Website Checks

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer-website#107]
Website checks are required according to https://whimsy.apache.org/pods/project/answer, and it seems that there're some gaps to fill.

**Navigation**
- [x] Add ASF dropdown menu, open in new window
- [x] Add Twitter menu, open in new window

**Footer**
- [x] Add Disclaimer, Trademarks and more
- [x] Remove social media link

**Others**
- [x] Stop link to externally hosted resources
- [x] #108

Check the [design files](https://www.figma.com/file/5nxbSDjPTlH1Uw8tYhFuiA/Official-Site?type=design&node-id=1-2&mode=design&t=6cUTheBWHdQDVjUG-4).

**Comment by fenbox** [comment]
@shuashuai Would you like to help improve this?

**Comment by sy-records** [comment]
@fenbox You can assign it to me.
