### ISSUE TITLE
Commit logo to apache.org/logos

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer-website#108]
Commit [logo](https://github.com/apache/incubator-answer-website/blob/main/static/img/logo-dark.svg) to `apache.org/logos` by [this way](https://www.apache.org/logos/about.html)

logo file named `answer.svg`

**Comment by kumfo** [comment]
Done.

https://svn.apache.org/repos/asf/comdev/project-logos/originals/answer.svg
