### ISSUE TITLE
404 on Homepage-ASF-Events

### ISSUE THREAD

**Issue by PrimmaAnna** [apache/incubator-answer-website#113]
The link that goes to https://www.apache.org/events/current-event displays 404. 
Does it need to be replaced with a new one? Should we inform Apache about this?

**Comment by tisonkun** [comment]
Please do not assign issues to others without proactive requesting. All contributors work in a volunteer bias instead of being assigned to finish the task as an employee.


ditto - https://github.com/apache/incubator-answer/issues/583#issuecomment-1780319536

**Comment by tisonkun** [comment]
Send an email - https://lists.apache.org/thread/21c8orfwm58px5olng05fcf46jmj307k
