### ISSUE TITLE
Feel confused about the contact address on the official website

### ISSUE THREAD

**Issue by LinuxSuRen** [apache/incubator-answer-website#117]
As you can see, it shows two email addresses that do not belong to apache.org. Especially there is a marketing contact. Who is the owner of the domain answer.dev.

![image](https://github.com/apache/incubator-answer/assets/1450685/feab77ea-0dba-488d-a35c-75c915fd9513)

**Comment by fenbox** [comment]
Thank you for reporting these issues, need to fix these outdated links.

- [ ] Change "Email us at ..." to "Mailing list dev@answer.apache.org"
- [ ] "Mailing list" section linked to https://lists.apache.org/list.html?dev@answer.apache.org
- [ ] Remove "Marketing Inquiries" section

**Comment by LinuxSuRen** [comment]
I'd happy to do it if it's ok.

**Comment by fenbox** [comment]
@LinuxSuRen Thank you and looking forward to it.
