### ISSUE TITLE
Some strings could not be found in crowdin

### ISSUE THREAD

**Issue by jihuayu** [apache/incubator-answer-website#141]
I could not find some menus translate keys in Crowdin, such as the "Getting Started" and "User Guides".
How can we translate it?

![image](https://github.com/apache/incubator-answer-website/assets/32858525/5faa5745-42bf-4c49-8c89-9ec79d992176)

**Comment by shuashuai** [comment]
I checked docusaurus's docs  and found that the configuration method provided by the official docusaurus did not take effect, so I directly manually modified the translation of the built-in template to customize the translation of these sidebar categories.
