### ISSUE TITLE
If  Answer official website needs animation effects?

### ISSUE THREAD

**Issue by LofiSu** [apache/incubator-answer-website#229]
like : https://michalsnik.github.io/aos/

**Comment by shuashuai** [comment]
Thank you very much for your advice, we don't need animation now. 

Of course, if you're interested, you can contribute a version with animations, and we'll ask the community to decide whether or not to adopt it.

**Comment by LofiSu** [comment]
> Thank you very much for your advice, we don't need animation now.
> 
> Of course, if you're interested, you can contribute a version with animations, and we'll ask the community to decide whether or not to adopt it.

ok I ll try to pull request.
