### ISSUE TITLE
Apache Answer Homepage -- English Grammar Issues

### ISSUE THREAD

**Issue by andrew-lawlor** [apache/incubator-answer-website#245]
Hi Everyone!

First off, I love what you're doing here! Answer is a great app. I've been testing it out recently and I even want to pitch it as a community Q&A solution for the small company that I work for.

I did notice a few grammatical issues on the website's homepage, however. I think improving these could help the app to project a more professional image, especially when it's reviewed by executives and decision makers. I hope this is the right venue for this kind of thing.

Here's what I found:
1. In the hero section, you should use the indefinite article 'a' before each item in the text carousel. For example, "Build a Support Center" or "Build a Knowledge Base" instead of "Build Support Center" etc. Using the indefinite article sounds much more natural to me as a native English speaker.
![image](https://github.com/user-attachments/assets/6d28e707-995d-4f64-97c3-9cef9f1776e3)
2. In the Q&A Platform card, the line "Your info keeping up-to-date and trusted." should be replaced with "Your info is kept up to date and trusted". I think perhaps a full rewrite is warranted here, but this change at least makes it grammatically correct so that it doesn't jump out at potential customers.
![image](https://github.com/user-attachments/assets/185d2c73-e094-4b5e-aa6b-303093b7f6db)
3. For the Organized card, I think it needs a full rewrite. The current text strikes me as a bit strange. Here is a suggestion: Organize questions and help content into categories with tags, making knowledge easy for others to find. Quickly locate answers using the search feature.
![image](https://github.com/user-attachments/assets/ccb7ac56-4b85-448c-b490-5d03237d7c0a)
4. For the integrations card, here is my suggestion: Extend Answers with plugins to integrate your favorite services. Improve your workflow, grow your community, and make your other tools better.
5. Gamification card -- Maybe something like this: We're adding gamification to the Q&A platform with reputation and badges. Put the fun back into work for both community members and teams!

I really think these small changes would add an additional layer of polish to the site, and might encourage more user adoption! 

Thanks,

Andrew L

**Comment by PrimmaAnna** [comment]
> Hi Everyone!
> 
> First off, I love what you're doing here! Answer is a great app. I've been testing it out recently and I even want to pitch it as a community Q&A solution for the small company that I work for.
> 
> I did notice a few grammatical issues on the website's homepage, however. I think improving these could help the app to project a more professional image, especially when it's reviewed by executives and decision makers. I hope this is the right venue for this kind of thing.
> 
> Here's what I found:
> 
> 1. In the hero section, you should use the indefinite article 'a' before each item in the text carousel. For example, "Build a Support Center" or "Build a Knowledge Base" instead of "Build Support Center" etc. Using the indefinite article sounds much more natural to me as a native English speaker.
>    ![image](https://private-user-images.githubusercontent.com/19480132/360025325-6d28e707-995d-4f64-97c3-9cef9f1776e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMTAwNjAsIm5iZiI6MTcyNjEwOTc2MCwicGF0aCI6Ii8xOTQ4MDEzMi8zNjAwMjUzMjUtNmQyOGU3MDctOTk1ZC00ZjY0LTk3YzMtOWNlZjlmMTc3NmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAyNTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3M2Q4OGUzNDM5ZmEwNjI0YWZkMGQ0NmRjZGQ1NjQxNjRhMjM3N2I0YTljYTIwZmQwOTM1NmZmNTBkZGViY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pZwT8i7gGRR9jLEa9yC3D7I3uSIF8P7jzUmBbXQLIzw)
> 2. In the Q&A Platform card, the line "Your info keeping up-to-date and trusted." should be replaced with "Your info is kept up to date and trusted". I think perhaps a full rewrite is warranted here, but this change at least makes it grammatically correct so that it doesn't jump out at potential customers.
>    ![image](https://private-user-images.githubusercontent.com/19480132/360026893-185d2c73-e094-4b5e-aa6b-303093b7f6db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMTAwNjAsIm5iZiI6MTcyNjEwOTc2MCwicGF0aCI6Ii8xOTQ4MDEzMi8zNjAwMjY4OTMtMTg1ZDJjNzMtZTA5NC00YjVlLWFhNmItMzAzMDkzYjdmNmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAyNTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4Mzg4YjhkZDY2NDc2ZDY3ODAzNzNkNmE3NjFiNjc0Yzc3MmIxNGM5ODg4ZTMxZDJlMmEzNWE5NzI4NTI3YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CqB-3YFUOFlUYC13pzTrGenYiUfUWv7xLoSYoGBR26k)
> 3. For the Organized card, I think it needs a full rewrite. The current text strikes me as a bit strange. Here is a suggestion: Organize questions and help content into categories with tags, making knowledge easy for others to find. Quickly locate answers using the search feature.
>    ![image](https://private-user-images.githubusercontent.com/19480132/360028363-ccb7ac56-4b85-448c-b490-5d03237d7c0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMTAwNjAsIm5iZiI6MTcyNjEwOTc2MCwicGF0aCI6Ii8xOTQ4MDEzMi8zNjAwMjgzNjMtY2NiN2FjNTYtNGI4NS00NDhjLWI0OTAtNWQwMzIzN2Q3YzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAyNTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YmRhZmQ4MjliNzEwNTY0ZTQ1MGRhNGUyYzhmNjU5OTU2MjQ2NWJmODM5Mjk1OWIzNWQwOWMzN2I1YTQ0NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PnaX8GCD6paPJfKW4KoT_-umLrPPOAxJ6mRbbOzRm6Y)
> 4. For the integrations card, here is my suggestion: Extend Answers with plugins to integrate your favorite services. Improve your workflow, grow your community, and make your other tools better.
> 5. Gamification card -- Maybe something like this: We're adding gamification to the Q&A platform with reputation and badges. Put the fun back into work for both community members and teams!
> 
> I really think these small changes would add an additional layer of polish to the site, and might encourage more user adoption!
> 
> Thanks,
> 
> Andrew L

Hi Andrew, thank you so much for your suggestion here. Here're the changes:
1. Add the indefinite article 'a' before the text carousel, that is a developer hub, a support center, a Q&A community, etc.
2. I rewrite the feature blocks, let's hear if you have any suggestions.
**Q&A Platform**
Ask, answer, and grow with the community. Everyone is a part of knowledge sharing: contribute an answer, leave a comment, and vote. The content is always up-to-date. 

**Always Organized**
Search and find relevant content with the help of intuitive tagging system. 
It’s an easy and efficient way for categorization. Everyone can search and locate the content quickly. 

**Integrations**
Extend Apache Answer with plugins to fit your needs. Connect with the tools you love. Streamline your workflow, add wings to current tools, and boost the efficiency. 

**Gamification**
Earn reputation and badges with your expertise and etiquette. Enjoy a rewarding and engaging experience while thrive the community with other members. 

Once again, thank you for your time and effort. We truly hope you had a nice pitch and Answer can be your community Q&A solution. Have a lovely day.
