### ISSUE TITLE
Use documents to add Chinese : 使用文档增加中文的建议

### ISSUE THREAD

**Issue by Dev-Wiki** [apache/incubator-answer-website#35]
[go - SegmentFault 思否正式开源问答社区软件 Answer - SegmentFault 思否之声 - SegmentFault 思否](https://segmentfault.com/a/1190000042672978)

思否社区 的用户过来的, 国际化是个好事情, 能否在使用说明层面增加本地化呢?  可能有不少从思否社区过来的用户, 不是每个人的英文都能否完整的阅读使用文档. 为了更好的推广让国内用户使用 是否考虑增加本地化的使用说明.

比如alist, 本身提供了 中英两种文档说明.

默认英文: [Home | AList Docs](https://alist.nn.ci/)

切换中文: [Home | AList文档](https://alist.nn.ci/zh/)

这个就好比本项目的issue 要求 使用英文说明问题 以更好的国际化, 方便国外用户. 

使用层面亦可以提供一份中文说明 方便国内用户.

英文可以国际化, 同样中文也可以.

**Comment by joyqi** [comment]
我们会在近期增加中文文档，并同时维护。因为项目发布周期比较短，所以前期只发布了英文文档。

希望大家也能一同帮助我们维护中文文档。
